name: DiscordBot

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers and run tests
        run: make test

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.test.yml down
