name: Test Discord Bot And Cogs

on:
  push:
    branches:
    - main
    - feature/**
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers and run tests
      run: docker-compose -f "docker-compose.test.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.test.yml" down
